### PR TITLE
Update README to Enhance Project Title with GIF for Improved Aesthetics (#453)

### PR DESCRIPTION
**Pull request by Karthik3904**
Related Issue: #453 

### **Pull Request Description:**
This pull request improves the visual appeal of the project by:
1. Adding a visually appealing GIF to the project title in the `README.md` file.
2. Centering the project title and GIF to enhance its prominence and create a more engaging introduction for users viewing the repository.

The changes aim to:
- Enhance user experience by making the project title more dynamic and attractive.
- Provide a clear and welcoming display at the top of the repository for new contributors and viewers.

Please label this PR with:
- gssoc-ext for contributions under GirlScript Summer of Code Extended.
- hacktoberfest-accepted to ensure it counts towards Hacktoberfest.

https://github.com/user-attachments/assets/24c1e63a-3431-4daa-90cc-5f7c1d596476

### CODE REVIEW

**Comment by Karthik3904** [comment]
If there is any issue let me know!

**Comment by Karthik3904** [comment]
Dear @Vin205  ,

I hope this message finds you well. I kindly request you to review and merge my pull request at your earliest convenience. Additionally, if the contribution meets your standards, please provide the hacktoberfest-accepted label.

Thank you for your time and consideration.

Best regards,
@Karthik3904

**Review by skmirajulislam — COMMENTED** [review]
good

**Comment by Karthik3904** [comment]
Thank You

**Pull request merged**
