### PR TITLE
Added image carousel in about section 

### PR DESCRIPTION
**Pull request by swatified**
**1) ADDED IMAGE CAROUSEL AND FIXED BG UI ISSUE IN ABOUT SECTION**

https://github.com/user-attachments/assets/e1bba825-9162-4692-a321-8f9116816731

**2) FIXED IMAGE HEIGHT IN HOME PAGE**

image

**3) IMPROVED MARGINS IN FAQ PAGE**

image

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@swatified please provide issue number!

**Comment by swatified** [comment]
@skmirajulislam this is regarding #51 Kindly assign me the required labels and level as you think its worth of, after a check!

**Review by skmirajulislam — APPROVED** [review]
@swatified please provide issue number so that i can merge it!

**Comment by swatified** [comment]
@skmirajulislam 51?

**Pull request merged**
