### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sadab-Hussain**
This fixes : #299

I have updated the README.md file to enhance the user experience by including screenshots of the project in both desktop and mobile views, as per the raised issue. The added screenshots provide a clearer understanding of the visual aspects of the project for users. 

You can check the screenshots below for both desktop and mobile views:

image
image

### CODE REVIEW

**Comment by Sadab-Hussain** [comment]
> place it at bottom not in top

which one ?

**Review by skmirajulislam — APPROVED** [review]

**Comment by skmirajulislam** [comment]
> > place it at bottom not in top
> 
> which one ?

your changes only

**Comment by Sadab-Hussain** [comment]
> > > place it at bottom not in top
> > 
> > 
> > which one ?
> 
> your changes only

**Comment by Sadab-Hussain** [comment]
Now Check: 
image

**Review by skmirajulislam — APPROVED** [review]

**Pull request merged**
