### PR TITLE
FIX THE NAVBAR add Hamburger #13

### PR DESCRIPTION
**Pull request by sahhoArjun097**
Implemented a responsive navigation bar that displays a hamburger menu on smaller screens.
The navigation menu is hidden on mobile until the hamburger icon is clicked, at which point it toggles the menu.

https://github.com/user-attachments/assets/693d622e-1fa4-4411-88b6-1d43f9ad38cf

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl according to the work.

issue number 13

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@sahhoArjun097 wait for a minute, until i evaluate the process of this PR

**Comment by sahhoArjun097** [comment]
change where made in hamburger to when i added footer section but i can't raise two PS at same time

**Comment by skmirajulislam** [comment]
@sahhoArjun097 okey that's why it's giving me the same changes update,

**Comment by skmirajulislam** [comment]
@sahhoArjun097 for this PR I'll give you only 1 point because this version is already available in main, as per #17, otherwise it will be considered as a rules violation of GSSoC extended & Hactoborfest

**Review by skmirajulislam — APPROVED** [review]

**Comment by sahhoArjun097** [comment]
okay

**Comment by skmirajulislam** [comment]
Please provide your current issue number

**Comment by sahhoArjun097** [comment]
#35

**Comment by skmirajulislam** [comment]
Not this one give me issue no

**Comment by skmirajulislam** [comment]
#13 is yours?

**Pull request merged**
