### PR TITLE
solved issue #47

### PR DESCRIPTION
**Pull request by Devanshu1603**
Added a scroll to top button on home page

### CODE REVIEW

**Comment by Devanshu1603** [comment]
@skmirajulislam  please review the PR and merge it accordingly .

**Comment by skmirajulislam** [comment]
@Devanshu1603 please provide your issue number

**Review by skmirajulislam — APPROVED** [review]
PR approved please provide an video demonstration with issue NO!

**Comment by Devanshu1603** [comment]
Solved issue #47 . Please merge  the pr under gssoc-extended and hacktober fest accepted levels.

Uploading Recording 2024-10-06 095704 (1).mp4…

**Comment by Devanshu1603** [comment]
Solved issue #47 . Please merge  the pr under gssoc-extended and hacktober fest accepted level.

https://github.com/user-attachments/assets/d4bba3f9-35c9-481b-8a25-7a38b994a8fb

**Comment by skmirajulislam** [comment]
@Devanshu1603 raise your PR,

**Pull request closed without merging**
