### PR TITLE
Secure Firebase keys, fix duplicate navbar issue, and prepare for authentication

### LINKED ISSUE #74: 🎉 New Release: Project Structure Updated - Backend Added! 🚀
### 📁 What's New?
We’ve made significant updates to the project structure! A **new backend folder** has been added to the repository to improve scalability and organization. This is a crucial step for the ongoing development of the project.

### 🔧 What You Need to Do:
All contributors, **please make sure to update your local repositories** by running the following command:

```bash
git pull origin main
```

**Important:** If you do not update your local repository, your pull requests **WILL NOT** be accepted. It is essential to keep your version up to date with the new structure.

### 💡 Contribution Guidelines:
1. **Hacktoberfest & GSSoC Participation:** We are open for contributions as part of Hacktoberfest and GSSoC. Please ensure you follow the guidelines for both events while contributing to this repository.
   
2. **Pull Request Requirements:**
   - Ensure your local version is up to date with the latest structure.
   - Follow the **first-come, first-served** principle when claiming issues and submitting pull requests.
   - Make sure your PRs align with the **Hacktoberfest** and **GSSoC** contribution rules for valid submissions.
   
3. **New Features & Bug Fixes:**
   - We’re now accepting contributions for the newly added backend.
   - Check out the [Issues](https://github.com/your-repo/issues) tab for tasks available for contribution.

### ⚠️ Attention:
Any pull requests from outdated repositories will be **rejected**. Please ensure you update your local version before contributing to avoid conflicts and ensure smooth collaboration.

### 🙌 Thank You!
We appreciate your dedication and contributions! Let’s work together to build something amazing and make Hacktoberfest & GSSoC 2024 a huge success!

### PR DESCRIPTION
**Pull request by VaibhavKatariya**
### Summary
Before starting work on **fix #74**, I identified a critical security issue where the Firebase configuration keys were publicly exposed. To address this, I created a `.env` file and added a `.env.sample` file containing the structure for the Firebase configuration. 🔒

Here’s the content of the `.env.sample` file:

``` bash
REACT_APP_FIREBASE_API_KEY=
REACT_APP_FIREBASE_AUTH_DOMAIN=
REACT_APP_FIREBASE_PROJECT_ID=
REACT_APP_FIREBASE_STORAGE_BUCKET=
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=
REACT_APP_FIREBASE_APP_ID=
```

### Other Fixes
Additionally, I resolved a duplicate navbar error and fixed import spacing issues.

### Next Steps
I will now proceed with implementing authentication using Firebase.

### Maintainer Note
@skmirajulislam  It’s imperative to keep Firebase keys private to prevent unauthorized access to the database and other sensitive data. This issue must be treated with the utmost seriousness to safeguard the project. 🚨

Also please add `hacktoberfest`, `gssoc-ext` and `level 2` label

### CODE REVIEW

**Comment by skmirajulislam** [comment]
Thank you for your PR. However, I won’t be able to award you 2 points for this submission as the navbar issue has already been resolved by Devanshu, who has received the reward for it. The change you've made is relatively minor, so I can award you 1 point for this.

Additionally, I would like to remind you not to create multiple issues and PRs for a single task. I’ve already listed the complete implementation, and once that is done, you’ll receive the full 3 points at once.

**Comment by VaibhavKatariya** [comment]
Thank you for your feedback! I understand the point about not creating multiple issues or PRs for a single task. However, since the exposure of the Firebase configuration keys was a serious security issue, I felt it was necessary to create a PR to address that.

**Comment by skmirajulislam** [comment]
@VaibhavKatariya this issue is reviewed by @Vin205 wait till evolution!

**Comment by VaibhavKatariya** [comment]
@skmirajulislam, the code is working. Since it's taking too long to review, could you please add hacktoberfest and hacktoberfest-accepted labels in the meantime?

Thanks!

**Comment by VaibhavKatariya** [comment]
@skmirajulislam Why has this been marked as invalid? It was a security concern, which is why I made the changes. At the very least, it should not have been marked as invalid since it's not a spam. I'm honestly quite disappointed.

**Comment by skmirajulislam** [comment]
@VaibhavKatariya i already told you dont raise multiple PR for same, in your recent PR update tracked thats why!

**Pull request closed without merging**
