### PR TITLE
Update the entire directory structure

### PR DESCRIPTION
**Pull request by rko0211**
Kindly review my PR and merge it under Hacktoberfest 2024.
Resolve issue: #25

If you have any problem let me know.. Thank you

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@rko0211 The site continues to function correctly after restructuring the file organization, demonstrating successful implementation and compatibility. could you please provide a video demonstration

**Comment by skmirajulislam** [comment]
@rko0211 please provide a video demonstration and resolve branch conflicts so that we can able to merge it to main

**Comment by rko0211** [comment]
Kindly review my PR



https://github.com/user-attachments/assets/191bf5ce-2a5a-4222-b804-eeb448820d9f

**Review by skmirajulislam — APPROVED** [review]
@rko0211 changes accepted!

**Pull request merged**
