### PR TITLE
Implement Login, Signup, and Logout Features with Dashboard Route (Fix #89)

### LINKED ISSUE #89: adding authentication feature
Once the application prompts for login and sign-in, we can work on authentication. Please address this issue with relevant tags under GSSOC and Hacktoberfest.

### PR DESCRIPTION
**Pull request by VaibhavKatariya**
### Description
This pull request is related to #89  and introduces the following features:

- **Login**: Users can log in using their email and password.
- **Signup**: New users can create accounts with email and password authentication.
- **Logout**: Users can log out from their sessions seamlessly.
- **Dashboard Route**: A placeholder dashboard route has been created, which currently serves as a dummy page.

For the time being, the username field has been removed, and authentication is limited to email and password. I plan to reintroduce the username feature once this PR is merged.

### Next Steps
- Please ensure that email/password authentication is enabled in the Firebase console for this feature to function correctly.
- Further enhancements, including the reintroduction of the username feature, will be developed after the current changes are merged.

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@VaibhavKatariya give a video demonstration it' ll help us a lot during review & murks evolution.

**Comment by skmirajulislam** [comment]
@VaibhavKatariya show database information where data being stored give me an view of it. then i can merge it!

**Review by skmirajulislam — APPROVED** [review]

**Comment by VaibhavKatariya** [comment]
Since Firebase Auth is being used, you can see the users directly in the Firebase Console under the Authentication section. I noticed that the authentication was not enabled in your Firebase project, so I created my own project for testing purposes. Below is a screenshot of how the user data looks in the Firebase Console.

image

**Comment by skmirajulislam** [comment]
> Since Firebase Auth is being used, you can see the users directly in the Firebase Console under the Authentication section. I noticed that the authentication was not enabled in your Firebase project, so I created my own project for testing purposes. Below is a screenshot of how the user data looks in the Firebase Console.
> 
> image

accepted

**Pull request merged**
