### PR TITLE
added login signup pages

### PR DESCRIPTION
**Pull request by adityalaxkar123**
# add the login and signup pages

### CODE REVIEW

**Comment by adityalaxkar123** [comment]
Screenshot (966)
Screenshot (967)
Screenshot (968)
Screenshot (969)

**Comment by adityalaxkar123** [comment]
my issue no. is #3

**Review by skmirajulislam — APPROVED** [review]

**Comment by adityalaxkar123** [comment]
What I have to do

**Comment by skmirajulislam** [comment]
@adityalaxkar123 wait till PA will review!

**Comment by skmirajulislam** [comment]
@Vin205 please resolve the branch conflicts before merging it to main.

**Comment by adityalaxkar123** [comment]
Conflicts resolved

**Comment by skmirajulislam** [comment]
@adityalaxkar123 congrats for your Contribution ⭐

**Pull request merged**
