### PR TITLE
Added AI Chatbot to the Website

### PR DESCRIPTION
**Pull request by linga-007**
under frontend folder  , in the .env file , kindly place your own GROQ_API key and run the project

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@linga-007 please video demonstration! AND YOUR ISSUE NUMBER!

**Comment by skmirajulislam** [comment]
@linga-007 hey there is problem in deployment with your PR, raise your fresh PR!

**Comment by linga-007** [comment]
https://github.com/user-attachments/assets/73eef951-be18-4ebf-a4a6-5dab90f226c3

issue number 139

**Comment by linga-007** [comment]
kindly check your vercel dashboard and let me know why the deployment failed

**Comment by skmirajulislam** [comment]
issue number please

**Review by skmirajulislam — APPROVED** [review]

**Comment by linga-007** [comment]
issue number : 100

**Comment by skmirajulislam** [comment]
@Vin205 please resolve this issue, i'm having trouble to accesing vercel pre version,please resolve it your side!

**Pull request closed without merging**
