### PR TITLE
Updated Responsiveness

### PR DESCRIPTION
**Pull request by SatyaJaiss**
The site is now responsive to all screen sizes.

https://github.com/user-attachments/assets/e22d93db-f43b-481b-9f01-35c2e8291923

@skmirajulislam Kindly review.

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@SatyaJaiss please provide your issue no!

**Review by skmirajulislam — APPROVED** [review]
@SatyaJaiss your changes are accepted please provide your issue no!

**Comment by SatyaJaiss** [comment]
#41

**Comment by skmirajulislam** [comment]
@SatyaJaiss please solve this branch conflicts so that i can merge it to main!, congrats for your contribution ✨

**Review by skmirajulislam — APPROVED** [review]

**Review by skmirajulislam — APPROVED** [review]

**Pull request merged**
