### PR TITLE
Multi-Language Support Using Language Translator

### PR DESCRIPTION
**Pull request by TBorundia**
Issue : #348
I have added Multi-Language Support Using Language Translator API that will helps to convert the website text to the multiple country languages.

https://github.com/user-attachments/assets/ad11cd72-c94f-4598-b047-56bb6a34986a

### CODE REVIEW

**Comment by TBorundia** [comment]
@Vin205 , Please review this PR. Thank You!

**Comment by TBorundia** [comment]
@Vin205 , Please review this PR. Thank You!

**Comment by TBorundia** [comment]
@Vin205 @skmirajulislam , 
Please review this PR. Thank You!

**Comment by Vin205** [comment]
Please resolve the conlicts

**Comment by TBorundia** [comment]
@Vin205 , Conflicts are solved .
Please review it. Thank you!!

**Comment by TBorundia** [comment]
@Vin205  , I have resolved the conflicts .
Please review it as soon as possible. Thank You!!

**Comment by TBorundia** [comment]
@Vin205 @skmirajulislam  , I have resolved the conflicts .
Please review and merge it. Thank You!!

**Comment by TBorundia** [comment]
@Vin205 , please review it !!

**Comment by TBorundia** [comment]
@skmirajulislam , please review it !!

**Comment by TBorundia** [comment]
@skmirajulislam , @Vin205 
Please review and merge it. Thank You!!

**Pull request closed without merging**
