### PR TITLE
BUG: Improving the Allignment of ContactUs page

### LINKED ISSUE #276: BUG: ContactUs Section hide
Contact us section hide by navbar of the website it don't show the whole page of contactUs.

UI of ContactUs Page:

https://github.com/user-attachments/assets/8c3cd17c-cbb8-474a-97e1-f00ed62e55ce

@skmirajulislam Please assign this issue to under gssoc-ext, hacktoberfest-accepted with level-2.

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #276 Improving the allignment of ContactUs page now it will not hide by the navbar of the website:)

@skmirajulislam Please review it and merge accordingly!

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@skmirajulislam Please review??

**Comment by harshbhar0629** [comment]
@skmirajulislam Please review and merge it:)

**Review by skmirajulislam — APPROVED** [review]

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Comment by harshbhar0629** [comment]
@shreya-paul-17 what's happening.?

**Review by MastanSayyad — COMMENTED** [review]
Hi @Vin205 Program Manager this side, kindly reduce the label from level 2 to level 1 as the chnages are just minor CSS properties!

Also please add me as a collaborator in your repo as we are reviewing the repo we need to reduce the levels from some contributors! thank you.

**Pull request merged**
