### PR TITLE
Enhanced Loan Section

### LINKED ISSUE #407: [Custom]: UI improvement in loan section
# 💡 Custom Issue

### 📝 Description
Redesigning of the page

### 🎯 Expected Outcome
Keeping the basic details same, I will present it in the more appealing and attractive way

### PR DESCRIPTION
**Pull request by Bhum-ika**
Fixed #407 

https://github.com/user-attachments/assets/4e25f28c-2eff-42a2-8ce7-0afde480929d

### CODE REVIEW

**Comment by skmirajulislam** [comment]
wait for PA review

**Comment by Bhum-ika** [comment]
@skmirajulislam how long is it going to take

**Comment by Vin205** [comment]
Your branch has conflicts please resolve them

**Comment by Bhum-ika** [comment]
I have raise a PR. please check. This one got some issues

**Pull request closed without merging**
