### PR TITLE
logo updated

### PR DESCRIPTION
**Pull request by adityakr0660**
logo updated #42 
logo1

@skmirajulislam kindly review, if you need any changes, let me know

### CODE REVIEW

**Comment by adityakr0660** [comment]
It seems like working on a Level 2 task for creating a new logo and i should be considered.

**Comment by skmirajulislam** [comment]
@adityakr0660 KINDLY RESOLVE branch conflicts so that i can merge it!

**Review by skmirajulislam — APPROVED** [review]
@adityakr0660 changes approved, please resolve the branch conflicts!

**Comment by adityakr0660** [comment]
Why you are rejected this bhaiya?

**Comment by adityakr0660** [comment]
why you rejected this ? @skmirajulislam

**Comment by skmirajulislam** [comment]
@adityakr0660 sorry for that our PA @Vin205 dont like this, that's why i closed this PR!
feel free for new contributions!

**Pull request closed without merging**
