### PR TITLE
Additon of All Contributors | Issue #53

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added all the contributors in readme.md file to give them appreciation.
Completed #53 

image

### CODE REVIEW

**Comment by skmirajulislam** [comment]
> I have added all the contributors in readme.md file to give them appreciation. Completed #53
> 
> image

its dynamic ?

**Comment by Shariq2003** [comment]
> > I have added all the contributors in readme.md file to give them appreciation. Completed #53
> > image
> 
> its dynamic ?

Yes

**Review by skmirajulislam — APPROVED** [review]
@Shariq2003 your PR is approved!

**Comment by Shariq2003** [comment]
@skmirajulislam okay, i am checking....

**Pull request merged**
