### PR TITLE
Edit: Design login and signup page

### LINKED ISSUE #49: Designing login / signup page
There must be a login/signup page please assign me this task under gssoc-extended , hacktober fest and with appropriate level. will be happy to contribute

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #49 Editing done for login and signup page now button also navigate to login and signup page accordingly!

@skmirajulislam  Please review my PR and merge accordingly with the label....according to your requirement its working fine now:)

Test video: 

https://github.com/user-attachments/assets/ddcaa692-ce5f-46e5-a6a3-6b2314fadb01

### CODE REVIEW

**Review by skmirajulislam — APPROVED** [review]
@harshbhar0629 your changes are approved, please resolve branch conflict, so that i can merge it!

**Comment by harshbhar0629** [comment]
Ok, I'll try to resolve
@skmirajulislam

**Review by skmirajulislam — APPROVED** [review]

**Comment by skmirajulislam** [comment]
> package-lock.json package.json When we are downloading dependency of this project then version occur different.

project is already updated twice current version is 2.1 check #74 guidelines.

**Comment by skmirajulislam** [comment]
Hi @harshbhar0629,

Thank you for your contribution! Unfortunately, someone has already submitted a PR that addresses the issue before your branch conflict was resolved. As a result, I will be closing this PR.

Please feel free to contribute to other functionalities in the project. If you have any questions or need assistance, don’t hesitate to ask.

**Pull request closed without merging**
