### PR TITLE
solved issue #47

### PR DESCRIPTION
**Pull request by Devanshu1603**
added a scroll to top button on home page. please review the PR and merge it accordingly.

### CODE REVIEW

**Comment by Devanshu1603** [comment]
@anurags10  how to resolve these conflicts.

**Comment by skmirajulislam** [comment]
open your pr and remove branch logs

**Comment by Devanshu1603** [comment]
how to remove the branch logs. can you explain please

**Review by skmirajulislam — CHANGES_REQUESTED** [review]
fix the branch conflicts!

**Comment by skmirajulislam** [comment]
> ### This branch has conflicts that must be resolved
> Use the command line to resolve conflicts before continuing.
> #### Conflicting files
> `src/Hom.css`
> `src/Hom.js`

git checkout master
git pull
git checkout <branch>
git merge master
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by Devanshu1603** [comment]
facing following problem 
Screenshot 2024-10-06 011000

**Comment by skmirajulislam** [comment]
> facing following problem Screenshot 2024-10-06 011000

do it in some IDE like VS code

**Comment by Devanshu1603** [comment]
i couldn't understand how to do it . can you explain step wise step

**Pull request closed without merging**
