### PR TITLE
Fixed the homepage ui #31

### PR DESCRIPTION
**Pull request by swatified**
I added an animation in hero page and improved overall style of the app, making it look more professional and trustworthy. See the images here: 
Screenshot 2024-10-05 000506
Screenshot 2024-10-05 000518
Screenshot 2024-10-05 000528
Screenshot 2024-10-05 001514

Let me know how I did. I am new to open source. @skmirajulislam

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@swatified I'm very satisfied with these changes, raise your PR I'll give a point there that you deserve, based on your hardwork and dedication

**Comment by swatified** [comment]
This is in regarding my issue #31 i am sorry it didnt get linked properly @skmirajulislam. kindly fix the issue and assign me tags and level before merging

**Review by skmirajulislam — APPROVED** [review]
@swatified please fix the branch conflict so I can merge it to main branch of this project.

**Comment by swatified** [comment]
@skmirajulislam Conflicts have been fixed

**Comment by skmirajulislam** [comment]
Wait a sec for evaluation ✅

**Pull request merged**
