### PR TITLE
add chatbot  integration to website

### PR DESCRIPTION
**Pull request by amanver45**
https://github.com/user-attachments/assets/2be7f2aa-a805-4dfd-9536-6a33db4dfa84

#326

### CODE REVIEW

**Comment by amanver45** [comment]
@Vin205 check this pr

**Comment by amanver45** [comment]
@Vin205 check this pr

**Comment by Vin205** [comment]
The branch has conflicts please resolve them

**Comment by amanver45** [comment]
Why close this issue @Vin205

**Comment by amanver45** [comment]
Pls tell

**Comment by amanver45** [comment]
Ok

**Pull request closed without merging**
