### PR TITLE
FIX THE NAVBAR add Hamburger #13

### PR DESCRIPTION
**Pull request by sahhoArjun097**
Implemented a responsive navigation bar that displays a hamburger menu on smaller screens.
The navigation menu is hidden on mobile until the hamburger icon is clicked, at which point it toggles the menu.

https://github.com/user-attachments/assets/693d622e-1fa4-4411-88b6-1d43f9ad38cf

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl according to the work.

### CODE REVIEW

**Comment by skmirajulislam** [comment]
@sahhoArjun097 what is your issue number ?

**Comment by sahhoArjun097** [comment]
#34

**Comment by sahhoArjun097** [comment]
#13

**Comment by skmirajulislam** [comment]
Okey let me check the changes, till  wait for confirmation

**Review by skmirajulislam — APPROVED** [review]

**Review by skmirajulislam — COMMENTED** [review]
Please fix the branch conflict so that i can merge it to main,

**Comment by sahhoArjun097** [comment]
the change is already done  when  you merge ADD FOOTER SECTION TO THE PAGE #14 #17 but i didn't raise this PR

**Comment by sahhoArjun097** [comment]
#35

**Pull request closed without merging**
