### PR TITLE
ADD FOOTER SECTION TO THE PAGE #14

### PR DESCRIPTION
**Pull request by sahhoArjun097**
I ADD footer section to all the pages in the website and the footer section is fully responsive and add
transition effect to the social links.

https://github.com/user-attachments/assets/b079331a-0e89-4ba5-9116-4e8e05b56fc0

### CODE REVIEW

**Comment by sahhoArjun097** [comment]
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant  and lvl.

**Review by skmirajulislam — COMMENTED** [review]
There’s an unwanted white gap between two sections on the webpage. It’s usually caused by extra margin, padding, or other CSS layout properties. Here’s how to fix it:

Inspect the Elements: Use the browser’s Developer Tools (usually F12 or right-click > Inspect) to check the margin, padding, or other layout properties applied to the sections.

CSS Adjustments:

Set the margin and padding of the sections to 0 or reduce them where needed.

Check for Floating or Alignment Issues: Sometimes floats or incorrect display properties can cause gaps. You might need to clear floats or adjust the layout model with flexbox or grid.

Let me know if you need specific guidance based on your code setup, and I’ll help accordingly! Once the issue is fixed, you can notify the team with an update like:

"The white gap issue between the two sections has been resolved. Please review the upgrade and confirm if everything looks good!"

**Comment by sahhoArjun097** [comment]
Added Footer Section: Introduced a new footer section to the page to improve the overall structure and user experience.

Animation Effects: Applied smooth animation effects to the footer elements to enhance visual appeal and interactivity.

Responsive Design: Ensured that the footer section is fully responsive across various screen sizes. Adjustments were made to ensure that the content adapts well from large desktop screens to smaller mobile devices.

Additional Changes: Tweaked some layout and style settings in the main section to align with the new footer and ensure consistency across the site.

**Review by skmirajulislam — APPROVED** [review]

**Comment by skmirajulislam** [comment]
@sahhoArjun097 congrats for your contribution 👍,

**Comment by sahhoArjun097** [comment]
hello can you please increase the level of thIs PR

**Comment by sahhoArjun097** [comment]
thank you sir

**Comment by skmirajulislam** [comment]
@sahhoArjun097 yap sure for your handwork well do it

**Comment by sahhoArjun097** [comment]
navbar is almost ready is there is any discord link i need to ask you something

**Comment by skmirajulislam** [comment]
@sahhoArjun097 you can follow me on 
LinkedIn: https://www.linkedin.com/in/sk-mirajul-islam-876438261/
Discord: sk_miraj

**Pull request merged**
