### PR TITLE
add chatbot integration to website 

### PR DESCRIPTION
**Pull request by amanver45**
#326 

https://github.com/user-attachments/assets/388909b3-b353-4e14-9040-63354ca6283d

### CODE REVIEW

**Comment by amanver45** [comment]
@Vin205 pls check this pr

**Comment by amanver45** [comment]
@Vin205 lls check

**Comment by amanver45** [comment]
@Vin205

**Comment by amanver45** [comment]
@Vin205  i raise new pt check this

**Review by skmirajulislam — APPROVED** [review]

**Pull request merged**
