### PR TITLE
Updated FAQ for small devices

### PR DESCRIPTION
**Pull request by Sarthakkashyapp**
Updated the FAQ's section for small devices with additional functionality and arrows everything is working fine now for medium and small devices, and also updated some meaningful answers and styling. 

Screenshot 2024-10-15 221828

Screenshot 2024-10-16 144206

resolved issue #293.

Thankyou so much for the opportunity. @skmirajulislam.

please add the labels **hacktoberfest-accepted**, **gssoc-ext** and **level1**.

### CODE REVIEW

**Comment by Sarthakkashyapp** [comment]
@skmirajulislam kindly merge this under the labels and once again Thankyou so much for the opportunity. It was great working on this project.

**Review by skmirajulislam — APPROVED** [review]

**Comment by Sarthakkashyapp** [comment]
@skmirajulislam sure I will do it.

**Comment by Sarthakkashyapp** [comment]
@skmirajulislam I think the conflicts have been resolved as I am working on a clean tree and also not able to click Resolve conflicts option. to double check I have also checked on the editor.  
 
Screenshot 2024-10-16 165046
                                                                                                                        
Screenshot 2024-10-16 164618.

**Comment by skmirajulislam** [comment]
> @skmirajulislam I think the conflicts have been resolved as I am working on a clean tree and also not able to click Resolve conflicts option. to double check I have also checked on the editor. I think it is ready to merge. Thankyou so much for your time and once again thankyou for the opportunity😊.
> 
> Screenshot 2024-10-16 165046
> 
> Screenshot 2024-10-16 164618.

raise an fresh Pr for it, make sure this time don't create an extra branch which may create conflicts on new one after ``git pull``

**Comment by Sarthakkashyapp** [comment]
Okay @skmirajulislam will raise a new a new PR for this 👍🏻.

**Comment by skmirajulislam** [comment]
> Okay @skmirajulislam will raise a new a new PR for this 👍🏻.

okey pointed!

**Comment by Sarthakkashyapp** [comment]
@skmirajulislam It is showing me everything thing up-to-date I don't think without making a creating a new branch it will be possible raise a new PR.

**Comment by Sarthakkashyapp** [comment]
Should I delete the current feature branch then make a new branch and then raise a fresh PR?

**Comment by skmirajulislam** [comment]
> Should I delete the current feature branch then make a new branch and then raise a fresh PR?

yeh

**Comment by skmirajulislam** [comment]
I'm closing this PR, raise your new updated PR

**Pull request closed without merging**
