### PR TITLE
Bug: Misalignment Footer

### LINKED ISSUE #369: [BUG]: Inconsistent Alignment of Login and Footer Containers
#### 📋 Description
The current alignment of the login and footer containers is inconsistent, resulting in a poor user interface experience. Both the login and footer containers are horizontally aligned, which causes the layout to appear cluttered and unstructured. For a more polished look, these elements should be vertically aligned to enhance the visual flow and overall aesthetics of the page.

#### ⚙️ Steps to Reproduce
1. Navigate to the login page.
2. Observe the alignment of the login container and footer.
3. Note that both are horizontally aligned, which disrupts the intended UI layout.

#### ✔️ Expected Behavior
The login and footer containers should be vertically aligned for a clean and structured appearance, providing a consistent visual experience.

#### ❌ Actual Behavior
Both the login and footer containers are aligned horizontally, causing the interface to appear disorganized and detracting from the overall user experience.

#### 📷 Screenshots
image

#### 🖥️ Environment (if applicable):
- **OS**: Windows 11
- **Browser**: Chrome, Firefox, Brave

#### 🔧 Additional Information
Vertical alignment of the containers would create a more user-friendly layout and improve the visual hierarchy on the page.

Please assign this issue to me under gssoc-ext level2 and hactoberfest-accecpted, @Vin205  , as I am interested in working on it.

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #369 #371 Now footer will be removed from login and signup page and form will be not misaligned now:)

@skmirajulislam Please review my PR and merge accordingly:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@skmirajulislam I resolved 2 issue in single pull request please give to me credit for both issue:)

**Comment by harshbhar0629** [comment]
@skmirajulislam  I resolved 2 issue in single pull request please give to me credit for both issue:)

**Comment by harshbhar0629** [comment]
@skmirajulislam Please review:)

**Review by skmirajulislam — APPROVED** [review]

**Comment by harshbhar0629** [comment]
@skmirajulislam Do you want the footer in bottom of login and signup.?

**Comment by skmirajulislam** [comment]
no wait till i resolve internal conflict server side, everything is fine

**Comment by harshbhar0629** [comment]
Ok after resolving please merge my PR:)

**Comment by harshbhar0629** [comment]
@skmirajulislam Please review again now conflict are resolved.

**Comment by skmirajulislam** [comment]
Wait 🫷🫷🫷

**Comment by skmirajulislam** [comment]
There is a big issue on the server side

**Comment by skmirajulislam** [comment]
writing to bring to your attention an issue with the recent changes made in the repository. Unfortunately, the current dependency updates have caused a fatal error in the Vercel runtime, resulting in the entire repository crashing.

To resolve this, I kindly request that you update the current dependency by using git pull or, if necessary, fork the repository anew. Please make the required changes and raise the PR carefully, ensuring that it addresses the crash issue in the runtime.

**Comment by harshbhar0629** [comment]
Ok i fork again and again create a PR

**Comment by harshbhar0629** [comment]
#430 Please accept the PR

**Pull request closed without merging**
